ALTER TABLE album DROP CONSTRAINT album_pk;
ALTER TABLE album ADD PRIMARY KEY (serial_num);

ALTER TABLE artist DROP CONSTRAINT artist_pk;
ALTER TABLE artist ADD PRIMARY KEY (serial_num);

ALTER TABLE stock DROP CONSTRAINT stock_pk;
ALTER TABLE stock ADD PRIMARY KEY (serial_num);

COMMIT;